version: "2.1"
services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
     # - PASSWORD=password     ## Uncomment to enable basic authentication, username = podgrab
    volumes:
      - /opt/podgrab/config:/config
      - /opt/podgrab/data:/assets
    ports:
      - 8080:8080
    restart: unless-stopped
